/* Generated By:JavaCC: Do not edit this line. ASTParserConstants.java */
package com.digiarea.es5.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ASTParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TAB = 1;
  /** RegularExpression Id. */
  int VT = 2;
  /** RegularExpression Id. */
  int FF = 3;
  /** RegularExpression Id. */
  int SP = 4;
  /** RegularExpression Id. */
  int NBSP = 5;
  /** RegularExpression Id. */
  int BOM = 6;
  /** RegularExpression Id. */
  int USP = 7;
  /** RegularExpression Id. */
  int LF = 8;
  /** RegularExpression Id. */
  int CR = 9;
  /** RegularExpression Id. */
  int LS = 10;
  /** RegularExpression Id. */
  int PS = 11;
  /** RegularExpression Id. */
  int EOL = 12;
  /** RegularExpression Id. */
  int NO_SKIP_EOL = 13;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 14;
  /** RegularExpression Id. */
  int JS_DOC_COMMENT = 17;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 18;
  /** RegularExpression Id. */
  int BREAK = 20;
  /** RegularExpression Id. */
  int CONTINUE = 21;
  /** RegularExpression Id. */
  int DELETE = 22;
  /** RegularExpression Id. */
  int ELSE = 23;
  /** RegularExpression Id. */
  int FOR = 24;
  /** RegularExpression Id. */
  int FUNCTION = 25;
  /** RegularExpression Id. */
  int IF = 26;
  /** RegularExpression Id. */
  int IN = 27;
  /** RegularExpression Id. */
  int NEW = 28;
  /** RegularExpression Id. */
  int RETURN = 29;
  /** RegularExpression Id. */
  int THIS = 30;
  /** RegularExpression Id. */
  int TYPEOF = 31;
  /** RegularExpression Id. */
  int VAR = 32;
  /** RegularExpression Id. */
  int VOID = 33;
  /** RegularExpression Id. */
  int WHILE = 34;
  /** RegularExpression Id. */
  int WITH = 35;
  /** RegularExpression Id. */
  int CASE = 36;
  /** RegularExpression Id. */
  int CATCH = 37;
  /** RegularExpression Id. */
  int CLASS = 38;
  /** RegularExpression Id. */
  int CONST = 39;
  /** RegularExpression Id. */
  int DEBUGGER = 40;
  /** RegularExpression Id. */
  int _DEFAULT = 41;
  /** RegularExpression Id. */
  int DO = 42;
  /** RegularExpression Id. */
  int ENUM = 43;
  /** RegularExpression Id. */
  int EXPORT = 44;
  /** RegularExpression Id. */
  int EXTENDS = 45;
  /** RegularExpression Id. */
  int FINALLY = 46;
  /** RegularExpression Id. */
  int IMPORT = 47;
  /** RegularExpression Id. */
  int SUPER = 48;
  /** RegularExpression Id. */
  int SWITCH = 49;
  /** RegularExpression Id. */
  int THROW = 50;
  /** RegularExpression Id. */
  int TRY = 51;
  /** RegularExpression Id. */
  int INSTANCEOF = 52;
  /** RegularExpression Id. */
  int TRUE = 53;
  /** RegularExpression Id. */
  int FALSE = 54;
  /** RegularExpression Id. */
  int NULL = 55;
  /** RegularExpression Id. */
  int GET = 56;
  /** RegularExpression Id. */
  int SET = 57;
  /** RegularExpression Id. */
  int LET = 58;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 59;
  /** RegularExpression Id. */
  int HEX_LITERAL = 60;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 61;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 62;
  /** RegularExpression Id. */
  int EXPONENT = 63;
  /** RegularExpression Id. */
  int STRING_LITERAL = 64;
  /** RegularExpression Id. */
  int SINGLE_STRING_LITERAL_BODY = 65;
  /** RegularExpression Id. */
  int DOUBLE_STRING_LITERAL_BODY = 66;
  /** RegularExpression Id. */
  int UNTERMINATED_STRING_LITERAL = 67;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_LITERAL = 68;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_BODY = 69;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_CHAR = 70;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_FIRST_CHAR = 71;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_BACKSLASH_SEQUENCE = 72;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_CLASS = 73;
  /** RegularExpression Id. */
  int REGULAR_EXPRESSION_CLASS_CHAR = 74;
  /** RegularExpression Id. */
  int IDENTIFIER = 75;
  /** RegularExpression Id. */
  int IDENTIFIER_START = 76;
  /** RegularExpression Id. */
  int IDENTIFIER_PART = 77;
  /** RegularExpression Id. */
  int UNICODE_LETTER = 78;
  /** RegularExpression Id. */
  int UNICODE_ESCAPE_SEQUENCE = 79;
  /** RegularExpression Id. */
  int UNICODE_COMBINING_MARK = 80;
  /** RegularExpression Id. */
  int UNICODE_DIGIT = 81;
  /** RegularExpression Id. */
  int UNICODE_CONNECTOR_PUNCTUATION = 82;
  /** RegularExpression Id. */
  int ZWNJ = 83;
  /** RegularExpression Id. */
  int ZWJ = 84;
  /** RegularExpression Id. */
  int HEX_DIGIT = 85;
  /** RegularExpression Id. */
  int LPAREN = 86;
  /** RegularExpression Id. */
  int RPAREN = 87;
  /** RegularExpression Id. */
  int LBRACE = 88;
  /** RegularExpression Id. */
  int RBRACE = 89;
  /** RegularExpression Id. */
  int LBRACKET = 90;
  /** RegularExpression Id. */
  int RBRACKET = 91;
  /** RegularExpression Id. */
  int SEMICOLON = 92;
  /** RegularExpression Id. */
  int COMMA = 93;
  /** RegularExpression Id. */
  int DOT = 94;
  /** RegularExpression Id. */
  int ASSIGN = 95;
  /** RegularExpression Id. */
  int GT = 96;
  /** RegularExpression Id. */
  int LT = 97;
  /** RegularExpression Id. */
  int BANG = 98;
  /** RegularExpression Id. */
  int TILDE = 99;
  /** RegularExpression Id. */
  int HOOK = 100;
  /** RegularExpression Id. */
  int COLON = 101;
  /** RegularExpression Id. */
  int STRICT_EQ = 102;
  /** RegularExpression Id. */
  int STRICT_NEQ = 103;
  /** RegularExpression Id. */
  int EQ = 104;
  /** RegularExpression Id. */
  int LE = 105;
  /** RegularExpression Id. */
  int GE = 106;
  /** RegularExpression Id. */
  int NE = 107;
  /** RegularExpression Id. */
  int SC_OR = 108;
  /** RegularExpression Id. */
  int SC_AND = 109;
  /** RegularExpression Id. */
  int INCR = 110;
  /** RegularExpression Id. */
  int NL_INCR = 111;
  /** RegularExpression Id. */
  int DECR = 112;
  /** RegularExpression Id. */
  int NL_DECR = 113;
  /** RegularExpression Id. */
  int PLUS = 114;
  /** RegularExpression Id. */
  int MINUS = 115;
  /** RegularExpression Id. */
  int STAR = 116;
  /** RegularExpression Id. */
  int SLASH = 117;
  /** RegularExpression Id. */
  int BIT_AND = 118;
  /** RegularExpression Id. */
  int BIT_OR = 119;
  /** RegularExpression Id. */
  int XOR = 120;
  /** RegularExpression Id. */
  int REM = 121;
  /** RegularExpression Id. */
  int LSHIFT = 122;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 123;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 124;
  /** RegularExpression Id. */
  int PLUSASSIGN = 125;
  /** RegularExpression Id. */
  int MINUSASSIGN = 126;
  /** RegularExpression Id. */
  int STARASSIGN = 127;
  /** RegularExpression Id. */
  int SLASHASSIGN = 128;
  /** RegularExpression Id. */
  int ANDASSIGN = 129;
  /** RegularExpression Id. */
  int ORASSIGN = 130;
  /** RegularExpression Id. */
  int XORASSIGN = 131;
  /** RegularExpression Id. */
  int REMASSIGN = 132;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 133;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 134;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 135;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int NOREGEXP = 1;
  /** Lexical state. */
  int NOEOL = 2;
  /** Lexical state. */
  int IN_JS_DOC_COMMENT = 3;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\u000b\"",
    "\"\\f\"",
    "\" \"",
    "\"\\u00a0\"",
    "\"\\ufeff\"",
    "<USP>",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\u2028\"",
    "\"\\u2029\"",
    "<EOL>",
    "<NO_SKIP_EOL>",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 15>",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 19>",
    "\"break\"",
    "\"continue\"",
    "\"delete\"",
    "\"else\"",
    "\"for\"",
    "\"function\"",
    "\"if\"",
    "\"in\"",
    "\"new\"",
    "\"return\"",
    "\"this\"",
    "\"typeof\"",
    "\"var\"",
    "\"void\"",
    "\"while\"",
    "\"with\"",
    "\"case\"",
    "\"catch\"",
    "\"class\"",
    "\"const\"",
    "\"debugger\"",
    "\"default\"",
    "\"do\"",
    "\"enum\"",
    "\"export\"",
    "\"extends\"",
    "\"finally\"",
    "\"import\"",
    "\"super\"",
    "\"switch\"",
    "\"throw\"",
    "\"try\"",
    "\"instanceof\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "\"get\"",
    "\"set\"",
    "\"let\"",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<STRING_LITERAL>",
    "<SINGLE_STRING_LITERAL_BODY>",
    "<DOUBLE_STRING_LITERAL_BODY>",
    "<UNTERMINATED_STRING_LITERAL>",
    "<REGULAR_EXPRESSION_LITERAL>",
    "<REGULAR_EXPRESSION_BODY>",
    "<REGULAR_EXPRESSION_CHAR>",
    "<REGULAR_EXPRESSION_FIRST_CHAR>",
    "<REGULAR_EXPRESSION_BACKSLASH_SEQUENCE>",
    "<REGULAR_EXPRESSION_CLASS>",
    "<REGULAR_EXPRESSION_CLASS_CHAR>",
    "<IDENTIFIER>",
    "<IDENTIFIER_START>",
    "<IDENTIFIER_PART>",
    "<UNICODE_LETTER>",
    "<UNICODE_ESCAPE_SEQUENCE>",
    "<UNICODE_COMBINING_MARK>",
    "<UNICODE_DIGIT>",
    "<UNICODE_CONNECTOR_PUNCTUATION>",
    "\"\\u200d\"",
    "\"\\u200c\"",
    "<HEX_DIGIT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"===\"",
    "\"!==\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "<NL_INCR>",
    "\"--\"",
    "<NL_DECR>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
  };

}
